/*
Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
package main

func main() {
	var fibo, f1, f2, sum int
	f1 = 3
	f2 = 5
	for true {
		fibo = f1 + f2
		f1 = f2
		f2 = fibo
		if fibo%2 == 0 {
			sum += fibo
		}
		if fibo > 4000000 {
			break
		}
	}
	println(sum + 2) //first even number we have to added
}
